#!/bin/bash
. /etc/vrsmsd.conf
while true
do

        wget --timeout=2  -t 3 --post-data "{\"cmd\":\"delete\",\"id\":-99,\"stream_id\":\"-99\"}"  http://$DAEMON_PORT:8888/postserver -O /dev/null > /dev/null 2>&1
        if [ $? != 0 ]; then
	    killall -9 fconv
            vrsmsd
            echo "setup director"
        fi

        sleep 3
	vrsync
	if [ $? != 0 ]; then
	    #echo "Authorization expired"
	    killall _vrsmsz
	fi
	let enc=`nvidia-smi dmon -c 1 | awk '{print $7}' | grep '[0-9]'`
	echo "$enc"
	if [ $enc -eq 0 ];then
		echo "nvidia error $enc"
                wget --timeout=2  -t 3 --post-data "{\"cmd\":\"refresh\"}"  http://$DAEMON_PORT:8888/postserver -O /dev/null > /dev/null 2>&1
	fi
done

exit 0
