#!/bin/bash
pid=`ps aux | grep _daemon | grep -v grep | cut -d ' ' -f 4`
kill -9 $pid > /dev/null 2>&1 
pid=`ps aux | grep runserver | grep -v grep | cut -d ' ' -f 4`
kill -9 $pid > /dev/null 2>&1
killall _vrsmsz > /dev/null 2>&1 
nohup _daemon > /tmp/vrsmsd.d 2>&1 &
