#!/bin/bash
_vrsmszpid=`ps aux | grep _vrsmsz | grep -v grep | grep -v daemon | awk '{print $2}' | grep '[0-9]'`
_daemonid=`ps aux | grep _daemon | grep -v color | awk '{print $2}' | grep '[0-9]'`
runserverpar=`ps aux | grep runserver | grep -v grep  | awk '{print $2}' | grep '[0-9]' | head -1`
runserverchd=`ps aux | grep runserver | grep -v grep  | awk '{print $2}' | grep '[0-9]' | tail -1`
cacheid=`ps aux | grep cache.sh | grep -v grep | awk '{print $2}' | grep '[0-9]'`

pid=$_daemonid
kill -9 $pid > /dev/null 2>&1 
pid=$_vrsmszpid
kill -9 $pid > /dev/null 2>&1
pid=$runserverpar
kill -9 $pid > /dev/null 2>&1
pid=$runserverchd
kill -9 $pid > /dev/null 2>&1
pid=$cacheid
sudo kill -9 $pid > /dev/null 2>&1
killall -9 nginx > /dev/null  2>&1
/usr/local/bin/trafficserver stop
killall -9 vrsmszd vrsmsz > /dev/null 2>&1
if [ $# -eq 0 ] ; then
   nohup _daemon > /tmp/.xxycc 2>&1 &
fi
