#!/bin/bash

export GST_PLUGIN_PATH=/usr/local/lib64/plugins
export LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/lib
ROOT_PATH=/usr/local
sudo nvidia-smi -pm 1
sudo nvidia-smi -ac 5003,1592
#sudo killall cache.sh > /dev/null 2>&1 
#sudo /usr/local/bin/cache.sh > /dev/null 2>&1 &
ulimit -c 0
source /etc/vrsmsd.conf
#$LD_LIBRARY_PATH/../nginx/sbin/nginx -s stop
$ROOT_PATH/nginx/sbin/nginx -p $ROOT_PATH/nginx 
$ROOT_PATH/bin/trafficserver start
killall _vrsmsz > /dev/null 2>&1 
cat /tmp/vrsmsd.log >> /tmp/vrsmsd.log.1
sleep 3
_vrsmsz $RTMP_HOST $RTMP_PORT $MODE $EXTERNAL_INTERFACE > /tmp/vrsmsd.log 2>&1 &
cd /var/local/vrsmsz/env
. ./bin/activate
cd /var/local/vrsmsz/env/uploadmodule
python manage.py runserver 0.0.0.0:9999 > /tmp/upload.log 2>&1 &
deactivate
#sudo chown $USER.$USER -r /tmp
